<?php

namespace Database\Seeders;

use App\Models\Prediccion;
use Illuminate\Database\Seeder;

class PrediccionSeeder extends Seeder
{
    public function run(): void
    {
        $predicciones = [
            ['prediccion_id' => 1, 'imagen_id' => 1, 'ritmo_id' => 6, 'probabilidad' => 0.9240, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 92.40}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 7.60}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-04-06 08:10:00'],
            ['prediccion_id' => 2, 'imagen_id' => 2, 'ritmo_id' => 7, 'probabilidad' => 0.9080, 'top_predicciones' => '[{"code": "STACH", "label": "Taquicardia Sinusal", "probability": 90.80}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 9.20}]', 'label_detectado' => 'Taquicardia Sinusal', 'label_code' => 'STACH', 'tipo' => 'arritmia', 'created_at' => '2026-04-06 09:25:00'],
            ['prediccion_id' => 3, 'imagen_id' => 3, 'ritmo_id' => 1, 'probabilidad' => 0.9310, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 93.10}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 6.90}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-06 10:40:00'],
            ['prediccion_id' => 4, 'imagen_id' => 4, 'ritmo_id' => 6, 'probabilidad' => 0.8870, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 88.70}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 11.30}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-04-07 08:05:00'],
            ['prediccion_id' => 5, 'imagen_id' => 5, 'ritmo_id' => 1, 'probabilidad' => 0.9160, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 91.60}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 8.40}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-07 09:20:00'],
            ['prediccion_id' => 6, 'imagen_id' => 6, 'ritmo_id' => 1, 'probabilidad' => 0.9420, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 94.20}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 5.80}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-07 10:35:00'],
            ['prediccion_id' => 7, 'imagen_id' => 7, 'ritmo_id' => 1, 'probabilidad' => 0.8090, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 80.90}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 19.10}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-07 11:50:00'],
            ['prediccion_id' => 8, 'imagen_id' => 8, 'ritmo_id' => 12, 'probabilidad' => 0.8950, 'top_predicciones' => '[{"code": "AFLT", "label": "Flutter Auricular", "probability": 89.50}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 10.50}]', 'label_detectado' => 'Flutter Auricular', 'label_code' => 'AFLT', 'tipo' => 'arritmia', 'created_at' => '2026-04-08 08:15:00'],
            ['prediccion_id' => 9, 'imagen_id' => 9, 'ritmo_id' => 1, 'probabilidad' => 0.9270, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 92.70}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 7.30}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-08 09:30:00'],
            ['prediccion_id' => 10, 'imagen_id' => 10, 'ritmo_id' => 6, 'probabilidad' => 0.9480, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 94.80}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 5.20}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-04-09 08:00:00'],
            ['prediccion_id' => 11, 'imagen_id' => 11, 'ritmo_id' => 7, 'probabilidad' => 0.9120, 'top_predicciones' => '[{"code": "STACH", "label": "Taquicardia Sinusal", "probability": 91.20}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 8.80}]', 'label_detectado' => 'Taquicardia Sinusal', 'label_code' => 'STACH', 'tipo' => 'arritmia', 'created_at' => '2026-04-09 09:15:00'],
            ['prediccion_id' => 12, 'imagen_id' => 12, 'ritmo_id' => 1, 'probabilidad' => 0.9040, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 90.40}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 9.60}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-09 10:30:00'],
            ['prediccion_id' => 13, 'imagen_id' => 13, 'ritmo_id' => 12, 'probabilidad' => 0.8890, 'top_predicciones' => '[{"code": "AFLT", "label": "Flutter Auricular", "probability": 88.90}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 11.10}]', 'label_detectado' => 'Flutter Auricular', 'label_code' => 'AFLT', 'tipo' => 'arritmia', 'created_at' => '2026-04-10 08:20:00'],
            ['prediccion_id' => 14, 'imagen_id' => 14, 'ritmo_id' => 1, 'probabilidad' => 0.9360, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 93.60}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 6.40}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-10 09:35:00'],
            ['prediccion_id' => 15, 'imagen_id' => 15, 'ritmo_id' => 1, 'probabilidad' => 0.9190, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 91.90}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 8.10}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-10 10:50:00'],
            ['prediccion_id' => 16, 'imagen_id' => 16, 'ritmo_id' => 6, 'probabilidad' => 0.9410, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 94.10}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 5.90}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-04-13 08:10:00'],
            ['prediccion_id' => 17, 'imagen_id' => 17, 'ritmo_id' => 1, 'probabilidad' => 0.9070, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 90.70}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 9.30}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-13 09:25:00'],
            ['prediccion_id' => 18, 'imagen_id' => 18, 'ritmo_id' => 7, 'probabilidad' => 0.8980, 'top_predicciones' => '[{"code": "STACH", "label": "Taquicardia Sinusal", "probability": 89.80}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 10.20}]', 'label_detectado' => 'Taquicardia Sinusal', 'label_code' => 'STACH', 'tipo' => 'arritmia', 'created_at' => '2026-04-14 08:05:00'],
            ['prediccion_id' => 19, 'imagen_id' => 19, 'ritmo_id' => 1, 'probabilidad' => 0.9250, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 92.50}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 7.50}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-14 09:20:00'],
            ['prediccion_id' => 20, 'imagen_id' => 20, 'ritmo_id' => 1, 'probabilidad' => 0.9140, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 91.40}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 8.60}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-14 10:35:00'],
            ['prediccion_id' => 21, 'imagen_id' => 21, 'ritmo_id' => 6, 'probabilidad' => 0.8060, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 80.60}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 19.40}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-04-14 11:50:00'],
            ['prediccion_id' => 22, 'imagen_id' => 22, 'ritmo_id' => 12, 'probabilidad' => 0.9090, 'top_predicciones' => '[{"code": "AFLT", "label": "Flutter Auricular", "probability": 90.90}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 9.10}]', 'label_detectado' => 'Flutter Auricular', 'label_code' => 'AFLT', 'tipo' => 'arritmia', 'created_at' => '2026-04-15 08:15:00'],
            ['prediccion_id' => 23, 'imagen_id' => 23, 'ritmo_id' => 1, 'probabilidad' => 0.9380, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 93.80}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 6.20}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-15 09:30:00'],
            ['prediccion_id' => 24, 'imagen_id' => 24, 'ritmo_id' => 1, 'probabilidad' => 0.9210, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 92.10}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 7.90}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-15 10:45:00'],
            ['prediccion_id' => 25, 'imagen_id' => 25, 'ritmo_id' => 6, 'probabilidad' => 0.9450, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 94.50}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 5.50}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-04-16 08:00:00'],
            ['prediccion_id' => 26, 'imagen_id' => 26, 'ritmo_id' => 1, 'probabilidad' => 0.9100, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 91.00}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 9.00}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-16 09:15:00'],
            ['prediccion_id' => 27, 'imagen_id' => 27, 'ritmo_id' => 1, 'probabilidad' => 0.8960, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 89.60}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 10.40}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-16 10:30:00'],
            ['prediccion_id' => 28, 'imagen_id' => 28, 'ritmo_id' => 7, 'probabilidad' => 0.9030, 'top_predicciones' => '[{"code": "STACH", "label": "Taquicardia Sinusal", "probability": 90.30}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 9.70}]', 'label_detectado' => 'Taquicardia Sinusal', 'label_code' => 'STACH', 'tipo' => 'arritmia', 'created_at' => '2026-04-17 08:20:00'],
            ['prediccion_id' => 29, 'imagen_id' => 29, 'ritmo_id' => 12, 'probabilidad' => 0.9280, 'top_predicciones' => '[{"code": "AFLT", "label": "Flutter Auricular", "probability": 92.80}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 7.20}]', 'label_detectado' => 'Flutter Auricular', 'label_code' => 'AFLT', 'tipo' => 'arritmia', 'created_at' => '2026-04-17 09:35:00'],
            ['prediccion_id' => 30, 'imagen_id' => 30, 'ritmo_id' => 1, 'probabilidad' => 0.9330, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 93.30}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 6.70}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-17 10:50:00'],
            ['prediccion_id' => 31, 'imagen_id' => 31, 'ritmo_id' => 6, 'probabilidad' => 0.9170, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 91.70}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 8.30}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-04-20 08:05:00'],
            ['prediccion_id' => 32, 'imagen_id' => 32, 'ritmo_id' => 1, 'probabilidad' => 0.8840, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 88.40}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 11.60}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-20 09:20:00'],
            ['prediccion_id' => 33, 'imagen_id' => 33, 'ritmo_id' => 1, 'probabilidad' => 0.9060, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 90.60}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 9.40}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-20 10:35:00'],
            ['prediccion_id' => 34, 'imagen_id' => 34, 'ritmo_id' => 7, 'probabilidad' => 0.8030, 'top_predicciones' => '[{"code": "STACH", "label": "Taquicardia Sinusal", "probability": 80.30}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 19.70}]', 'label_detectado' => 'Taquicardia Sinusal', 'label_code' => 'STACH', 'tipo' => 'arritmia', 'created_at' => '2026-04-20 11:50:00'],
            ['prediccion_id' => 35, 'imagen_id' => 35, 'ritmo_id' => 12, 'probabilidad' => 0.8990, 'top_predicciones' => '[{"code": "AFLT", "label": "Flutter Auricular", "probability": 89.90}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 10.10}]', 'label_detectado' => 'Flutter Auricular', 'label_code' => 'AFLT', 'tipo' => 'arritmia', 'created_at' => '2026-04-21 08:15:00'],
            ['prediccion_id' => 36, 'imagen_id' => 36, 'ritmo_id' => 1, 'probabilidad' => 0.9200, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 92.00}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 8.00}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-21 09:30:00'],
            ['prediccion_id' => 37, 'imagen_id' => 37, 'ritmo_id' => 6, 'probabilidad' => 0.9460, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 94.60}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 5.40}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-04-22 08:00:00'],
            ['prediccion_id' => 38, 'imagen_id' => 38, 'ritmo_id' => 1, 'probabilidad' => 0.9150, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 91.50}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 8.50}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-22 09:15:00'],
            ['prediccion_id' => 39, 'imagen_id' => 39, 'ritmo_id' => 1, 'probabilidad' => 0.9010, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 90.10}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 9.90}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-22 10:30:00'],
            ['prediccion_id' => 40, 'imagen_id' => 40, 'ritmo_id' => 7, 'probabilidad' => 0.8920, 'top_predicciones' => '[{"code": "STACH", "label": "Taquicardia Sinusal", "probability": 89.20}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 10.80}]', 'label_detectado' => 'Taquicardia Sinusal', 'label_code' => 'STACH', 'tipo' => 'arritmia', 'created_at' => '2026-04-23 08:20:00'],
            ['prediccion_id' => 41, 'imagen_id' => 41, 'ritmo_id' => 1, 'probabilidad' => 0.9340, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 93.40}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 6.60}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-23 09:35:00'],
            ['prediccion_id' => 42, 'imagen_id' => 42, 'ritmo_id' => 1, 'probabilidad' => 0.9220, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 92.20}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 7.80}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-23 10:50:00'],
            ['prediccion_id' => 43, 'imagen_id' => 43, 'ritmo_id' => 12, 'probabilidad' => 0.8880, 'top_predicciones' => '[{"code": "AFLT", "label": "Flutter Auricular", "probability": 88.80}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 11.20}]', 'label_detectado' => 'Flutter Auricular', 'label_code' => 'AFLT', 'tipo' => 'arritmia', 'created_at' => '2026-04-24 08:05:00'],
            ['prediccion_id' => 44, 'imagen_id' => 44, 'ritmo_id' => 1, 'probabilidad' => 0.9180, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 91.80}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 8.20}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-24 09:20:00'],
            ['prediccion_id' => 45, 'imagen_id' => 45, 'ritmo_id' => 1, 'probabilidad' => 0.9050, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 90.50}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 9.50}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-24 10:35:00'],
            ['prediccion_id' => 46, 'imagen_id' => 46, 'ritmo_id' => 6, 'probabilidad' => 0.9400, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 94.00}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 6.00}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-04-27 08:15:00'],
            ['prediccion_id' => 47, 'imagen_id' => 47, 'ritmo_id' => 1, 'probabilidad' => 0.9260, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 92.60}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 7.40}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-27 09:30:00'],
            ['prediccion_id' => 48, 'imagen_id' => 48, 'ritmo_id' => 1, 'probabilidad' => 0.9110, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 91.10}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 8.90}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-27 10:45:00'],
            ['prediccion_id' => 49, 'imagen_id' => 49, 'ritmo_id' => 1, 'probabilidad' => 0.8970, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 89.70}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 10.30}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-27 12:00:00'],
            ['prediccion_id' => 50, 'imagen_id' => 50, 'ritmo_id' => 7, 'probabilidad' => 0.9000, 'top_predicciones' => '[{"code": "STACH", "label": "Taquicardia Sinusal", "probability": 90.00}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 10.00}]', 'label_detectado' => 'Taquicardia Sinusal', 'label_code' => 'STACH', 'tipo' => 'arritmia', 'created_at' => '2026-04-28 08:00:00'],
            ['prediccion_id' => 51, 'imagen_id' => 51, 'ritmo_id' => 1, 'probabilidad' => 0.9300, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 93.00}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 7.00}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-28 09:15:00'],
            ['prediccion_id' => 52, 'imagen_id' => 52, 'ritmo_id' => 1, 'probabilidad' => 0.9230, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 92.30}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 7.70}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-28 10:30:00'],
            ['prediccion_id' => 53, 'imagen_id' => 53, 'ritmo_id' => 6, 'probabilidad' => 0.9470, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 94.70}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 5.30}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-04-29 08:20:00'],
            ['prediccion_id' => 54, 'imagen_id' => 54, 'ritmo_id' => 12, 'probabilidad' => 0.9130, 'top_predicciones' => '[{"code": "AFLT", "label": "Flutter Auricular", "probability": 91.30}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 8.70}]', 'label_detectado' => 'Flutter Auricular', 'label_code' => 'AFLT', 'tipo' => 'arritmia', 'created_at' => '2026-04-29 09:35:00'],
            ['prediccion_id' => 55, 'imagen_id' => 55, 'ritmo_id' => 1, 'probabilidad' => 0.8860, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 88.60}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 11.40}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-29 10:50:00'],
            ['prediccion_id' => 56, 'imagen_id' => 56, 'ritmo_id' => 7, 'probabilidad' => 0.9020, 'top_predicciones' => '[{"code": "STACH", "label": "Taquicardia Sinusal", "probability": 90.20}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 9.80}]', 'label_detectado' => 'Taquicardia Sinusal', 'label_code' => 'STACH', 'tipo' => 'arritmia', 'created_at' => '2026-04-30 08:05:00'],
            ['prediccion_id' => 57, 'imagen_id' => 57, 'ritmo_id' => 1, 'probabilidad' => 0.9290, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 92.90}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 7.10}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-04-30 09:20:00'],
            ['prediccion_id' => 58, 'imagen_id' => 58, 'ritmo_id' => 6, 'probabilidad' => 0.9440, 'top_predicciones' => '[{"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 94.40}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 5.60}]', 'label_detectado' => 'Fibrilacion Auricular', 'label_code' => 'AFIB', 'tipo' => 'arritmia', 'created_at' => '2026-05-04 08:15:00'],
            ['prediccion_id' => 59, 'imagen_id' => 59, 'ritmo_id' => 7, 'probabilidad' => 0.9160, 'top_predicciones' => '[{"code": "STACH", "label": "Taquicardia Sinusal", "probability": 91.60}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 8.40}]', 'label_detectado' => 'Taquicardia Sinusal', 'label_code' => 'STACH', 'tipo' => 'arritmia', 'created_at' => '2026-05-04 09:30:00'],
            ['prediccion_id' => 60, 'imagen_id' => 60, 'ritmo_id' => 1, 'probabilidad' => 0.8940, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 89.40}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 10.60}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-05-04 10:45:00'],
            ['prediccion_id' => 61, 'imagen_id' => 61, 'ritmo_id' => 1, 'probabilidad' => 0.9080, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 90.80}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 9.20}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-05-04 12:00:00'],
            ['prediccion_id' => 62, 'imagen_id' => 62, 'ritmo_id' => 12, 'probabilidad' => 0.9350, 'top_predicciones' => '[{"code": "AFLT", "label": "Flutter Auricular", "probability": 93.50}, {"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 6.50}]', 'label_detectado' => 'Flutter Auricular', 'label_code' => 'AFLT', 'tipo' => 'arritmia', 'created_at' => '2026-05-05 08:00:00'],
            ['prediccion_id' => 63, 'imagen_id' => 63, 'ritmo_id' => 1, 'probabilidad' => 0.9190, 'top_predicciones' => '[{"code": "NORM", "label": "Ritmo Sinusal Normal", "probability": 91.90}, {"code": "AFIB", "label": "Fibrilacion Auricular", "probability": 8.10}]', 'label_detectado' => 'Ritmo Sinusal Normal', 'label_code' => 'NORM', 'tipo' => 'normal', 'created_at' => '2026-05-05 09:15:00'],
        ];

        foreach ($predicciones as $p) {
            Prediccion::updateOrCreate(
                ['prediccion_id' => $p['prediccion_id']],
                [
                    'imagen_id' => $p['imagen_id'],
                    'ritmo_id' => $p['ritmo_id'],
                    'probabilidad' => $p['probabilidad'],
                    'tiempo_ms' => null,
                    'top_predicciones' => $p['top_predicciones'],
                    'label_detectado' => $p['label_detectado'],
                    'label_code' => $p['label_code'],
                    'tipo' => $p['tipo'],
                    'estado' => 1,
                    'created_at' => $p['created_at'],
                    'updated_at' => $p['created_at'],
                ]
            );
        }
    }
}
